"""Generate small, complete clients for deploying a selected prompt workflow."""

from __future__ import annotations

import json
from typing import Any, Literal

from pydantic import BaseModel

from prompt_playoff.domain import Exemplar, TaskProfile


class DeploymentBundle(BaseModel):
    name: str
    language: Literal["python", "typescript"]
    filename: str
    content: str
    config_filename: str
    config: str
    notes: list[str]


def export_runtime(
    *,
    task: TaskProfile,
    technique_id: str,
    language: Literal["python", "typescript"],
    response_schema: dict[str, Any] | None = None,
    variables: dict[str, str] | None = None,
    exemplars: list[Exemplar] | None = None,
) -> DeploymentBundle:
    """Export a client of `/v1/run`, which preserves every execution strategy.

    Keeping orchestration on the Prompt Playoff service means multi-stage,
    self-consistency, map-reduce, tool-loop and tree-search techniques all run
    exactly as benchmarked instead of being flattened into a single prompt.
    """
    config = {
        "task": task.model_dump(mode="json"),
        "technique_id": technique_id,
        "response_schema": response_schema,
        "variables": variables or {},
        "exemplars": [item.model_dump(mode="json") for item in (exemplars or [])],
        "timeout_seconds": 120,
    }
    config_json = json.dumps(config, indent=2, ensure_ascii=False)
    slug = technique_id.replace(".", "-")
    if language == "python":
        filename = f"run-{slug}.py"
        content = _python_client(config_json)
    else:
        filename = f"run-{slug}.ts"
        content = _typescript_client(config_json)
    return DeploymentBundle(
        name=f"{technique_id} deployment client",
        language=language,
        filename=filename,
        content=content,
        config_filename=f"{slug}.prompt-playoff.json",
        config=config_json + "\n",
        notes=[
            "Set PROMPT_PLAYOFF_URL when the service is not on http://127.0.0.1:8000.",
            "Provider secrets stay on the Prompt Playoff service and are not "
            "embedded in this export.",
            "The /v1/run endpoint executes every stage and strategy exactly as "
            "the benchmark runner does.",
        ],
    )


def _python_client(config_json: str) -> str:
    return f'''#!/usr/bin/env python3
"""Generated by Prompt Playoff. Requires Python 3.11+; no third-party packages."""
import json
import os
import sys
import urllib.error
import urllib.request

CONFIG = json.loads({config_json!r})


def run(user_input: str) -> str:
    payload = {{**CONFIG, "user_input": user_input}}
    url = os.getenv("PROMPT_PLAYOFF_URL", "http://127.0.0.1:8000").rstrip("/") + "/v1/run"
    request = urllib.request.Request(
        url,
        data=json.dumps(payload).encode("utf-8"),
        headers={{"Content-Type": "application/json"}},
        method="POST",
    )
    try:
        with urllib.request.urlopen(request, timeout=CONFIG["timeout_seconds"] + 5) as response:
            result = json.load(response)
    except urllib.error.HTTPError as exc:
        raise RuntimeError(exc.read().decode("utf-8", errors="replace")) from exc
    return result["output"]


if __name__ == "__main__":
    print(run(" ".join(sys.argv[1:]) or sys.stdin.read()))
'''


def _typescript_client(config_json: str) -> str:
    return f"""// Generated by Prompt Playoff. Runs on Node.js 20+ or a modern edge runtime.
const config = {config_json} as const;

export async function runPromptPlayoff(userInput: string): Promise<string> {{
  const baseUrl = (process.env.PROMPT_PLAYOFF_URL ?? "http://127.0.0.1:8000").replace(/\\/$/, "");
  const response = await fetch(`${{baseUrl}}/v1/run`, {{
    method: "POST",
    headers: {{ "Content-Type": "application/json" }},
    body: JSON.stringify({{ ...config, user_input: userInput }}),
    signal: AbortSignal.timeout((config.timeout_seconds + 5) * 1000),
  }});
  if (!response.ok) {{
    throw new Error(`Prompt Playoff ${{response.status}}: ${{await response.text()}}`);
  }}
  const result = (await response.json()) as {{ output: string }};
  return result.output;
}}
"""
